.MODEL SMALL
.STACK 100H

.DATA    

MSG20 DB '                ____________________________$'
MSG21 DB '               |                            |$'
MSG1  DB '               |       SELAMAT DATANG       |$'  
MSG22 DB '               |     DI QUIZ INFORMATIKA    |$'
MSG23 DB '               |____________________________|$'
MSG24 DB '$'
MSG25 DB 'Jawab : $'
MSG2 DB 'Syarat dan ketentuan : $'
MSG3 DB '- Quiz ini terdiri dari 5 Soal.$'
MSG4 DB '- Setiap user yang menjawab benar akan mendapatkan 1 point.$'
MSG5 DB 'Tekan ENTER untuk memulai Quiz... $'
MSG6 DB 'Jawaban Anda Benar.$'
MSG7 DB 'Jawaban Anda Salah.$'
MSG8 DB 'YEYYYY ANDA TELAH MENGISI QUIZ INFORMATIKA DENGAN LENGKAP.$'
MSG9 DB 'TOTAL POINT ANDA : $'
MSG10 DB 'Tekan 1 untuk mengulang Quiz atau Tekan 0 untuk Exit.$' 
MSG11 DB '                   ===== Terima Kasih =====$'
Q1 DB '1. Apa kepanjangan dari TRPL?$'
QA1  DB '   a) Teknologi Rekayasa Perangkat Lunak $'
QA11 DB '   b) Teknik Rekayasa Perangkat Lunak $'
QA111 DB '   c) Telekomunikasi Rekayasa Perangkat Lunak $'
Q2 DB '2. Program Studi TRPL merupakan bagian dari? $'
QA2 DB '   a) Sarjana IPB$'
QA22 DB '   b) Sekolah Vokasi IPB$'
QA222 DB '   c) Sekolah Bisnis IPB$'
Q3 DB '3. Siapakah Ketua Program Studi TRPL?$'
QA3 DB '   a) Medhanita Dewi Renanti, S.Kom, M.Kom$'
QA33 DB '   b) Sofiyanti Indriasari, S.Kom, M.Kom$'
QA333 DB '   c) Gema Parasti Mindara, S.Si, M.Kom$'
Q4 DB '4. Berikut mata kuliah Program Studi TRPL, kecuali?$'
QA4 DB '   a) Penerbitan dan Grafika$'
QA44 DB '   b) Produksi film dan video $'
QA444 DB '   c) Arsitektur dan Organisasi Komputer$'
Q5 DB '5. Gelar apakah yang akan didapat ketika lulus dari Program Studi TRPL?$'
QA5 DB '   a) Sarjana Terapan$'
QA55 DB '   b) Strata 1 (S1)$'
QA555 DB '   c) Ahli Madya$'


